const searchForm = document.getElementById('search-form');
const searchInput = document.getElementById('search-input');
const searchResults = document.getElementById('search-results');

searchForm.addEventListener('submit', function(event) {
    event.preventDefault();
    const searchTerm = searchInput.value.toLowerCase();
    const mockData = [
      { title: 'Must knows for muslims', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow.html' },
      { title: 'Proof for islam', url: 'https://islamiclibrary.github.io/pages/proof.html' },
      { title: 'Islamic law', url: 'https://islamiclibrary.github.io/pages/islamic_law.html' },
      { title: 'Anti-Islam', url: 'https://islamiclibrary.github.io/pages/anti_islam.html' },
      { title: 'Quranic preservation', url: 'https://islamiclibrary.github.io/pages/preservation.html' },
      { title: 'Islamic revert stories', url: 'https://islamiclibrary.github.io/pages/revert_stories.html' },
      { title: 'Other beliefs', url: 'https://islamiclibrary.github.io/pages/other_beliefs.html' },
      { title: '"Islamic"-Sects', url: 'https://islamiclibrary.github.io/pages/islamic_sects.html' },
      { title: 'Debunking Religions', url: 'https://islamiclibrary.github.io/pages/religion_debunking.html' },
      { title: 'Must watchs (coming soon)', url: 'https://islamiclibrary.github.io/pages/must_watch.html' },
      { title: 'Library', url: 'https://islamiclibrary.github.io/pages/library.html' },
      { title: 'Quick debunks', url: 'https://islamiclibrary.github.io/pages/quick.html' },
      { title: 'Refuting alleged Quranic errors', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_errors.html' },
      { title: 'Refuting alleged scientific errors', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors.html' },
      { title: 'Refuting / Explaining Hadith', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors.html' },
      { title: 'Refuting alleged Quranic problems', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_explanation.html' },
      { title: 'Refuting common allegations', url: 'https://islamiclibrary.github.io/pages/anti_islam/common_allegations.html' },
      { title: 'Refuting claims', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims.html' },
      { title: 'Alleged immorality', url: 'https://islamiclibrary.github.io/pages/anti_islam/immorality.html' },
      { title: 'Sam Shamoun', url: 'https://islamiclibrary.github.io/pages/anti_islam/sam_shamoun.html' },
      { title: '"Alternative fuer Deutschland" AFD', url: 'https://islamiclibrary.github.io/pages/anti_islam/afd.html' },
      { title: 'Nabeel Qureshi', url: 'https://islamiclibrary.github.io/pages/anti_islam/nabeel_qureshi.html' },
      { title: 'Dr. Jay Smith', url: 'https://islamiclibrary.github.io/pages/anti_islam/jay_smith.html' },
      { title: 'David Wood', url: 'https://islamiclibrary.github.io/pages/anti_islam/david_wood.html' },
      { title: '1000 Errors', url: 'https://islamiclibrary.github.io/pages/anti_islam/1000.html' },
      { title: 'Ruling with something other than shariah', url: 'https://islamiclibrary.github.io/pages/islamic_law/no_shariah_law.html' },
      { title: 'Beating slave girls', url: 'https://islamiclibrary.github.io/pages/islamic_law/beating_slave_girl.html' },
      { title: 'Adultress', url: 'https://islamiclibrary.github.io/pages/islamic_law/adultress.html' },
      { title: 'Celebrating holidays of the kuffar', url: 'https://islamiclibrary.github.io/pages/islamic_law/unislamic_holidays.html' },
      { title: 'Rape', url: 'https://islamiclibrary.github.io/pages/islamic_law/rape.html' },
      { title: 'Killing gay people', url: 'https://islamiclibrary.github.io/pages/islamic_law/killing_gays.html' },
      { title: 'Killing old people', url: 'https://islamiclibrary.github.io/pages/islamic_law/killing_old_people.html' },
      { title: 'Abdullah bin-sarh\'s apostasy', url: 'https://islamiclibrary.github.io/pages/islamic_law/abdullah_bin_sarhs.html' },
      { title: 'Apostasy law', url: 'https://islamiclibrary.github.io/pages/islamic_law/apostasy.html' },
      { title: 'Jizya', url: 'https://www.youtube.com/watch?v=_S02KBsu7rk' },
      { title: 'Destroying trees and buildings', url: 'https://islamiclibrary.github.io/pages/islamic_law/trees_temples.html' },
      { title: 'Music', url: 'https://islamiclibrary.github.io/pages/islamic_law/music.html' },
      { title: 'Slave running away', url: 'https://islamiclibrary.github.io/pages/islamic_law/running_slave.html' },
      { title: 'Best of women', url: 'https://islamiclibrary.github.io/pages/islamic_law/best_women.html' },
      { title: 'Inheritance', url: 'https://m.youtube.com/watch?v=7Rzj17yqCpA' },
      { title: 'Women in Islam', url: 'https://islamiclibrary.github.io/pages/islamic_law/women.html' },
      { title: 'Beating women', url: 'https://islamiclibrary.github.io/pages/islamic_law/beating_women.html' },
      { title: 'Aisha (ra) marriage', url: 'https://islamiclibrary.github.io/pages/islamic_law/aisha_marriage.html' },
      { title: 'How old was Aisha (ra)', url: 'https://islamiclibrary.github.io/pages/islamic_law/aisha_age.html' },
      { title: 'Shiism', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism.html' },
      { title: 'Ahmadiyya', url: 'https://islamiclibrary.github.io/pages/islamic_sects/ahmadiyya.html' },
      { title: 'Quranists', url: 'https://islamiclibrary.github.io/pages/islamic_sects/quranists.html' },
      { title: 'Khawarij', url: 'https://islamiclibrary.github.io/pages/islamic_sects/khawarij.html' },
      { title: 'Nation of Islam', url: 'https://islamiclibrary.github.io/pages/islamic_sects/nation_of_islam.html' },
      { title: 'Ismailism', url: 'https://islamiclibrary.github.io/pages/islamic_sects/ismailism.html' },
      { title: 'LGBTQIA+-"muslims"', url: 'https://islamiclibrary.github.io/pages/islamic_sects/lgbt.html' },
      { title: 'feminist-"muslims"', url: 'https://islamiclibrary.github.io/pages/islamic_sects/feminist.html' },
      { title: 'religious pluralism', url: 'https://islamiclibrary.github.io/pages/islamic_sects/pluralist.html' },
      { title: 'Hany Atchan and Abu Layth', url: 'https://islamiclibrary.github.io/pages/islamic_sects/hany.html' },
      { title: 'YT channels', url: 'https://islamiclibrary.github.io/pages/must_watch/yt.html' },
      { title: 'Debates', url: 'https://islamiclibrary.github.io/pages/must_watch/debates.html' },
      { title: 'Lectures', url: 'https://islamiclibrary.github.io/pages/must_watch/lectures.html' },
      { title: 'Quranic Arabic', url: 'https://islamiclibrary.github.io/books/book42.pdf' },
      { title: 'Fundamentals of Classical Arabic', url: 'https://islamiclibrary.github.io/books/book44.pdf' },
      { title: 'An introduction to Quranic and Classical Arabic', url: 'https://islamiclibrary.github.io/books/book45.pdf' },
      { title: 'is Islam a religion of Terror?', url: 'https://islamiclibrary.github.io/books/book1.pdf' },
      { title: 'How we must Interpret the Quran By Muhammad Al Albani', url: 'https://islamiclibrary.github.io/books/book2.pdf' },
      { title: 'Basics of Islam', url: 'https://islamiclibrary.github.io/books/book40.pdf' },
      { title: 'Tafsir Ibn Kathir', url: 'https://islamiclibrary.github.io/external/tafsir-ibn-kathir/' },
      { title: 'Ibn Taymiyyah explaination of Tafsir', url: 'https://islamiclibrary.github.io/external/ibn-taymiyyah-tafsir/' },
      { title: 'Hajj and Umrah Guide', url: 'https://islamiclibrary.github.io/books/book6.pdf' },
      { title: 'Polygamy in Islam', url: 'https://islamiclibrary.github.io/books/book7.pdf' },
      { title: 'The Rights of Non Muslim in Islamic World', url: 'https://islamiclibrary.github.io/books/book8.pdf' },
      { title: 'Setting the foundation for Prayer', url: 'https://islamiclibrary.github.io/books/book9.pdf' },
      { title: 'Ways for Gaining Rewards', url: 'https://islamiclibrary.github.io/books/book10.pdf' },
      { title: 'Human rights in Islam', url: 'https://islamiclibrary.github.io/books/book11.pdf' },
      { title: '100 ways to support the prophet ﷺ', url: 'https://islamiclibrary.github.io/books/book12.pdf' },
      { title: 'Muhammad ﷺ the last prophet!', url: 'https://islamiclibrary.github.io/books/book13.pdf' },
      { title: 'Obligation of Hijab', url: 'https://islamiclibrary.github.io/books/book14.pdf' },
      { title: 'The Way to Salvation', url: 'https://islamiclibrary.github.io/books/book15.pdf' },
      { title: 'Prophet ﷺ prophethood and Analytical View', url: 'https://islamiclibrary.github.io/books/book16.pdf' },
      { title: '33 Lessons for Every Muslim', url: 'https://islamiclibrary.github.io/books/book17.pdf' },
      { title: 'The Signs of the Hour', url: 'https://islamiclibrary.github.io/books/book18.pdf' },
      { title: 'Quran and Science', url: 'https://islamiclibrary.github.io/books/book19.pdf' },
      { title: 'The Day of Judgement', url: 'https://islamiclibrary.github.io/books/book20.pdf' },
      { title: 'The True Message of Jesus Christ', url: 'https://islamiclibrary.github.io/books/book21.pdf' },
      { title: 'The purpose of creation', url: 'https://islamiclibrary.github.io/books/book22.pdf' },
      { title: '44 ways to Manhood', url: 'https://islamiclibrary.github.io/books/book23.pdf' },
      { title: 'Winning the heart of your Wife', url: 'https://islamiclibrary.github.io/books/book24.pdf' },
      { title: 'Scientific and Islamic reason behind keeping a beard', url: 'https://islamiclibrary.github.io/books/book25.pdf' },
      { title: 'The Prophet ﷺ Best of all Husbands', url: 'https://islamiclibrary.github.io/books/book26.pdf' },
      { title: 'Muhammad ﷺ Messenger of Allah', url: 'https://islamiclibrary.github.io/books/book27.pdf' },
      { title: 'A Program of Studies for New Muslims', url: 'https://islamiclibrary.github.io/books/book28.pdf' },
      { title: 'The Islamic Ruling on Music and Singing', url: 'https://islamiclibrary.github.io/books/book29.pdf' },
      { title: 'What you must believe about your Creator', url: 'https://islamiclibrary.github.io/books/book30.pdf' },
      { title: 'The Righteous Husband and Wife', url: 'https://islamiclibrary.github.io/books/book31.pdf' },
      { title: 'Introduction to the Quran', url: 'https://islamiclibrary.github.io/books/book32.pdf' },
      { title: 'Obstacles in Seeking knowledge', url: 'https://islamiclibrary.github.io/books/book33.pdf' },
      { title: 'Restoring one’s Iman', url: 'https://islamiclibrary.github.io/books/book34.pdf' },
      { title: 'The Book of Manners', url: 'https://islamiclibrary.github.io/books/book35.pdf' },
      { title: 'Fundamentals of Tawheed', url: 'https://islamiclibrary.github.io/books/book36.pdf' },
      { title: 'Stories of the Prophets', url: 'https://islamiclibrary.github.io/books/book37.pdf' },
      { title: 'Pillars of Islam Vol. 1', url: 'https://islamiclibrary.github.io/books/book38.pdf' },
      { title: 'Pillars of Islam Vol. 2', url: 'https://islamiclibrary.github.io/books/book39.pdf' },
      { title: 'Book by Ibn Taymiyaah (RH) got Apologetics', url: 'https://islamiclibrary.github.io/external/ibn-taymiyyah-apologetics/' },
      { title: 'Download Islamic Books Here', url: 'https://islamiclibrary.github.io/external/islamic-books-download/' },
      { title: 'Tafsir As Saadi', url: 'https://islamiclibrary.github.io/books/book5.pdf' },
      { title: 'In defense of Islam', url: 'https://islamiclibrary.github.io/books/book41.pdf' },
      { title: 'Golden age of Jewish-Muslim relations', url: 'https://islamiclibrary.github.io/books/book43.pdf' },
      { title: 'Five pillars of Islam', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/islam_pillars.html' },
      { title: 'Six pillars of Iman', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/iman_pillars.html' },
      { title: 'Four Madhabs', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/four_madhabs.html' },
      { title: 'Fiqh of purification', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/purification.html' },
      { title: 'Fiqh of prayer', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/prayer.html' },
      { title: 'Fiqh of fasting', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/fasting.html' },
      { title: 'Fiqh of family', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/family.html' },
      { title: 'Fiqh of zakat', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/zakat.html' },
      { title: 'Fiqh of financial transactions', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/finance.html' },
      { title: 'Scholarly transmission', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/transmission.html' },
      { title: 'The conditions of forbidding evil', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/forbidding_evil.html' },
      { title: 'Halal and Haram', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/halal_haram.html' },
      { title: 'Merits of the Sahaba', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/sahaba_merits.html' },
      { title: 'Atheism', url: 'https://islamiclibrary.github.io/pages/other_beliefs/atheism.html' },
      { title: 'Taoism', url: 'https://islamiclibrary.github.io/pages/other_beliefs/taoism.html' },
      { title: 'Astrology', url: 'https://islamiclibrary.github.io/pages/other_beliefs/astrology.html' },
      { title: 'Buddhism', url: 'https://islamiclibrary.github.io/pages/other_beliefs/buddhism.html' },
      { title: 'Hinduism', url: 'https://islamiclibrary.github.io/pages/other_beliefs/hinduism.html' },
      { title: 'Satanism', url: 'https://islamiclibrary.github.io/pages/other_beliefs/satanism.html' },
      { title: 'Communism', url: 'https://islamiclibrary.github.io/pages/other_beliefs/communism.html' },
      { title: 'Socialism', url: 'https://islamiclibrary.github.io/pages/other_beliefs/socialism.html' },
      { title: 'Capitalism', url: 'https://islamiclibrary.github.io/pages/other_beliefs/capitalism.html' },
      { title: 'PERFECT YT video for easy and complete explanation', url: 'https://www.youtube.com/watch?v=ancam0X4Bf0' },
      { title: 'Textual', url: 'https://islamiclibrary.github.io/pages/preservation/textual.html' },
      { title: 'Why is Islam true?', url: 'https://islamiclibrary.github.io/pages/proof/true.html' },
      { title: 'Non muslim scholars on the Quran', url: 'https://islamiclibrary.github.io/pages/proof/non_muslims.html' },
      { title: 'Prophet Muhammad ﷺ', url: 'https://islamiclibrary.github.io/pages/proof/muhammad_saw.html' },
      { title: 'Prophecies of the prophet', url: 'https://islamiclibrary.github.io/pages/proof/prophecies.html' },
      { title: 'Linguistic miracles', url: 'https://islamiclibrary.github.io/pages/proof/linguistic_miracles.html' },
      { title: 'What would have happened without Islam', url: 'https://islamiclibrary.github.io/pages/proof/without_islam.html' },
      { title: 'Is prophet Muhammad ﷺ the author of the Quran?', url: 'https://islamiclibrary.github.io/pages/proof/quran_author.html' },
      { title: 'Miracles from the prophet Muhammad ﷺ', url: 'https://islamiclibrary.github.io/pages/proof/prophet_miracles.html' },
      { title: 'Was Muhammad ﷺ sent by Satan?', url: 'https://islamiclibrary.github.io/pages/proof/satan.html' },
      { title: 'What does Islam call for?', url: 'https://islamiclibrary.github.io/pages/proof/call.html' },
      { title: 'Was Joseph Smith like prophet Muhammad ﷺ?', url: 'https://islamiclibrary.github.io/pages/proof/joseph_smith.html' },
      { title: 'Scientific miracles', url: 'https://www.miracles-of-quran.com/' },
      { title: 'Atheism', url: 'https://islamiclibrary.github.io/pages/quick/Atheism.html' },
      { title: 'Christianity', url: 'https://islamiclibrary.github.io/pages/quick/Christianity.html' },
      { title: 'Judaism', url: 'https://islamiclibrary.github.io/pages/quick/Judaism.html' },
      { title: 'Zoroastrianism', url: 'https://islamiclibrary.github.io/pages/quick/Zoroastrianism.html' },
      { title: 'Buddhism', url: 'https://islamiclibrary.github.io/pages/quick/Buddhism.html' },
      { title: 'Tengrism', url: 'https://islamiclibrary.github.io/pages/quick/Tengrism.html' },
      { title: 'Hinduism', url: 'https://islamiclibrary.github.io/pages/quick/Hinduism.html' },
      { title: 'Deism', url: 'https://islamiclibrary.github.io/pages/quick/Deism.html' },
      { title: 'Sikhism', url: 'https://islamiclibrary.github.io/pages/quick/Sikhism.html' },
      { title: 'Quranism', url: 'https://islamiclibrary.github.io/pages/quick/Quranism.html' },
      { title: 'Qadianism', url: 'https://islamiclibrary.github.io/pages/quick/Qadianism.html' },
      { title: 'Liberalism', url: 'https://islamiclibrary.github.io/pages/quick/Liberalism.html' },
      { title: 'Bahaism', url: 'https://islamiclibrary.github.io/pages/quick/Bahaism.html' },
      { title: 'Paganism', url: 'https://islamiclibrary.github.io/pages/quick/Paganism.html' },
      { title: 'Druze', url: 'https://islamiclibrary.github.io/pages/quick/Druze.html' },
      { title: 'Agnosticism', url: 'https://islamiclibrary.github.io/pages/quick/Agnosticism.html' },
      { title: 'Ismailism', url: 'https://islamiclibrary.github.io/pages/quick/Ismailism.html' },
      { title: 'Christianity', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity.html' },
      { title: 'Judaism', url: 'https://islamiclibrary.github.io/pages/religion_debunking/judaism.html' },
      { title: 'Sikhism', url: 'https://islamiclibrary.github.io/pages/religion_debunking/sikhism.html' },
      { title: 'Zoroastrians', url: 'https://islamiclibrary.github.io/pages/religion_debunking/zoroastrians.html' },
      { title: 'Bahai', url: 'https://islamiclibrary.github.io/pages/religion_debunking/bahai.html' },
      { title: 'Ancient Mayan religion', url: 'https://islamiclibrary.github.io/pages/religion_debunking/mayans.html' },
      { title: 'Andrew Tate', url: 'https://www.youtube.com/watch?v=diqgTxR99JE' },
      { title: "Ibrahim X & Bobby's Perspective", url: 'https://www.youtube.com/live/5jqJIVRaErM?feature=share&t=562' },
      { title: 'Malcom X', url: 'https://www.youtube.com/watch?v=VHAzNCDKuvw' },
      { title: 'Muhammad Ali', url: 'https://www.youtube.com/watch?v=T4eKIEf7aH4' },
      { title: 'Kareem Abdul-Jabbar', url: 'https://www.youtube.com/live/5JWOGHkGM1Y?feature=share&t=1314' },
      { title: 'Mike Tyson', url: 'https://www.youtube.com/watch?v=QE1Y9RclFN4' },
      { title: 'Joram Van Klaveren', url: 'https://www.youtube.com/watch?v=yXCMU72z0Ms&t=6s' },
      { title: 'Dave Chappelle', url: 'https://www.youtube.com/watch?v=yV3E50laISI' },
      { title: 'Sara Bokker', url: 'https://www.youtube.com/watch?v=6HghEzLMy5E' },
      { title: 'Sneako', url: 'https://www.youtube.com/watch?v=eppGOkvTJ2w' },
      { title: 'Ali Dawah', url: 'https://www.youtube.com/watch?v=iSkWRezCnLw' },
      { title: 'Lauren Booth', url: 'https://youtu.be/O5fbyEV36pU' },
      { title: 'Did the Prophet SAW drink alcohol', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/alcohol.html' },
      { title: 'Aisha ra said Allah SWT serves Prophet Muhammad SAW', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/serving.html' },
      { title: 'Prophet SAW orders his wives to drink his pee', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/pee.html' },
      { title: 'Killing black dogs', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/black_dogs.html' },
      { title: 'The Prophet SAW cursing a lot', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/cursing.html' },
      { title: 'The Prophet SAW married his aunt', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/aunt.html' },
      { title: 'The Prophet SAW wanting a woman to be his queen', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/queen.html' },
      { title: 'Get tabook for yellow girls', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/tabook.html' },
      { title: 'Prophet SAW has sins quran sunnah', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/sinful.html' },
      { title: 'Jews claim Prophet Muhammad SAW is a terrorist', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/terrorist.html' },
      { title: 'Putting water between Fatimas', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/fatimas.html' },
      { title: 'Piercing eyes uranians', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/uranians.html' },
      { title: 'Prophet SAW wearing women cloth', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/women_cloth.html' },
      { title: 'Satanic verses', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/satan.html' },
      { title: 'Captives of awtas', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/awtas.html' },
      { title: 'Abu Sufyan raping the Prophet SAW', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/abu_sufyan.html' },
      { title: 'Entering upon um haram', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/um_haram.html' },
      { title: 'Slavery', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/Slavery.html' },
      { title: 'Prophet trading slaves', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/slavetrade.html' },
      { title: 'Anektaha hadith', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/anektaha.html' },
      { title: 'The Prophet SAW is a womanizer', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/womanizer.html' },
      { title: 'Magic argument', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/magic.html' },
      { title: 'Quran plagarized from poetry', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/poetry.html' },
      { title: 'Muhammad SAW killed 3000 people. Why not accept Joseph Smith', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/3000people.html' },
      { title: 'Killing Geckos', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/geckos.html' },
      { title: 'No people would succeed with women', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/succeed.html' },
      { title: 'Whoever contradicts islam is killed', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/killed.html' },
      { title: 'No witness to revelation', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/witness.html' },
      { title: 'Proposing marriage to a baby', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/babymarriage.html' },
      { title: 'Torturing a man for money', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/torturing.html' },
      { title: 'Necrophilia', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/Necrophilia.html' },
      { title: 'Abused woman with green skin hadith', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/green_skin.html' },
      { title: 'Right hand possession', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/Right_hand.html' },
      { title: 'Abu huraira copied Jewish texts', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/abu_huraira.html' },
      { title: 'Linguistic errors', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/linguistic.html' },
      { title: 'Abrogation', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/Abrogation.html' },
      { title: 'Moon god', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/Moon_god.html' },
      { title: 'Christians and Jews take on muslim\'s sins', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/taking_sins.html' },
      { title: 'Epilepsy argument', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/Epilepsy.html' },
      { title: 'Prophet gaining money from war booties', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/war_booties.html' },
      { title: 'Maryia Rayhana', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/Maryia.html' },
      { title: 'Muslims always respond with evil', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/evil.html' },
      { title: 'Makkah did not exist', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/makkah.html' },
      { title: 'Umar brougnt like the Quran', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/umar.html' },
      { title: 'Stoning monkeys', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/monkeys.html' },
      { title: 'Bond women awrah', url: 'https://islamiclibrary.github.io/pages/anti_islam/claims/awrah.html' },
      { title: 'Jews accusing the prophet of being lustful', url: 'https://islamiclibrary.github.io/pages/anti_islam/common_allegations/lustful.html' },
      { title: 'Allah SWT prays', url: 'https://islamiclibrary.github.io/pages/anti_islam/common_allegations/praying.html' },
      { title: 'Prophet SAW divorced because she had a white spot', url: 'https://islamiclibrary.github.io/pages/anti_islam/common_allegations/divorce.html' },
      { title: 'More than 4 wives', url: 'https://islamiclibrary.github.io/pages/anti_islam/common_allegations/4wives.html' },
      { title: 'Nikah means sex', url: 'https://islamiclibrary.github.io/pages/anti_islam/common_allegations/nikah.html' },
      { title: 'Allah SWT misguides', url: 'https://islamiclibrary.github.io/pages/anti_islam/common_allegations/misguides.html' },
      { title: 'Peace verses abrogated', url: 'https://islamiclibrary.github.io/pages/anti_islam/common_allegations/peace.html' },
      { title: 'Quran confirming Bible', url: 'https://islamiclibrary.github.io/pages/anti_islam/common_allegations/bible.html' },
      { title: 'Prophet SAW unsure of salvation', url: 'https://islamiclibrary.github.io/pages/anti_islam/common_allegations/salvation.html' },
      { title: 'Quran copying 7 sleepers', url: 'https://islamiclibrary.github.io/pages/anti_islam/common_allegations/7sleepers.html' },
      { title: 'Dhul Qarnayn was Alexander the Great', url: 'https://islamiclibrary.github.io/pages/anti_islam/common_allegations/dhul_qarnayn.html' },
      { title: 'Math errors', url: 'https://islamiclibrary.github.io/pages/anti_islam/common_allegations/math.html' },
      { title: 'Ring bell argument', url: 'https://islamiclibrary.github.io/pages/anti_islam/common_allegations/bell.html' },
      { title: 'Chainmail argument', url: 'https://islamiclibrary.github.io/pages/anti_islam/common_allegations/chainmail.html' },
      { title: 'Muslim 2127 beat Aisha', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/muslim_2127.html' },
      { title: 'Bukhari 6004 Aisha jealous', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_6004.html' },
      { title: 'Bukhari 2010 Taraweeh Bidah', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_2010.html' },
      { title: 'Bukhari 7142 racist hadith', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_7142.html' },
      { title: 'Majah 1986 hitting women', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/majah_1986.html' },
      { title: 'Bukhari 304 dumb women', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_304d.html' },
      { title: 'Dawud 2147 wife beating', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/dawud_2147.html' },
      { title: 'Dawud 4449 trust Tawrat', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/dawud_4449.html' },
      { title: 'Majah 1944 Sheep eating', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/majah_1944.html' },
      { title: 'Stoning Verse', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/stoning_verse.html' },
      { title: 'Suckling Verses', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/suckling_verses.html' },
      { title: 'Surah Ahzab 200 Verses', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/surah_ahzab.html' },
      { title: 'Bukhari 4428 poisoned', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_4428.html' },
      { title: 'Bukhari 6982 suicide', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_6982s.html' },
      { title: 'Muslim 2953a false prophecy', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/muslim_2953a.html' },
      { title: 'Bukhari 5083 forgetting Quran', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_5083.html' },
      { title: 'Tirmidhi 2861 jinns raped the prophet?', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/tirmidhi_2861.html' },
      { title: 'Muslim 1403 woman sheytan', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/muslim_1403.html' },
      { title: 'Bukhari 304 most women in hell', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_304m.html' },
      { title: 'Abi Dawid 4457 barbaric', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/abi_dawid_4457.html' },
      { title: 'Bukhari 6140 false prophecy', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_6140.html' },
      { title: 'Muslim 2643 embryology', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/muslim_2643.html' },
      { title: 'Majah 4337 72 hoories', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/majah_4337.html' },
      { title: 'Dawud 2386 prophet sucking toungues', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/dawud_2386.html' },
      { title: 'Dawud 4717 buried girls', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/dawud_4717.html' },
      { title: 'Bukhari 5825 abused women', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_5825.html' },
      { title: 'Muslim 510 donkey women dog', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/muslim_510.html' },
      { title: 'Bukhari 5215 lusting prophet', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_5215.html' },
      { title: 'Bukhari 3120 false prophecy', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_3120.html' },
      { title: 'Bukhari 2592', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_2592.html' },
      { title: 'Bukhari 5095', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_5095.html' },
      { title: 'Bukhari 2771', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_2771.html' },
      { title: 'Muslim 2363', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/muslim_2363.html' },
      { title: 'Bukhari 232 Semen', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_232.html' },
      { title: 'Muslim 1668a', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/muslim_1668a.html' },
      { title: 'Bukhari 4557', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_4557.html' },
      { title: 'Muslim 2167a', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/muslim_2167a.html' },
      { title: 'Bukhari 116 false prophecy?', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_116.html' },
      { title: 'Bukhari 25', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_25.html' },
      { title: 'Muslim 2898a', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/muslim_2898a.html' },
      { title: 'Bukhari 4814', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_4814.html' },
      { title: 'Bukhari 7116', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_7116.html' },
      { title: 'Bukhari 2583', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_2583.html' },
      { title: 'Bukhari 4697', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_4697.html' },
      { title: 'Muslim 1641a slavery', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/muslim_1641a.html' },
      { title: 'Bukhari 6982 angel attack', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_6982a.html' },
      { title: 'Muslim 612d horns of the devil during sunrise', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/muslim_612d.html' },
      { title: 'Ibn Masud', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/ibn_masud.html' },
      { title: 'Sahih al bukhari 2 ring sheytan', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_2.html' },
      { title: 'Sahih al bukhari 3399 & Muslim 1470d wives betraying the husband', url: 'https://islamiclibrary.github.io/pages/anti_islam/hadith_errors/bukhari_3399.html' },
      { title: 'Banu Quraidha Khaybar', url: 'https://islamiclibrary.github.io/pages/anti_islam/immorality/banu.html' },
      { title: 'Violent Verses', url: 'https://islamiclibrary.github.io/pages/anti_islam/immorality/violent.html' },
      { title: 'Killing critics', url: 'https://islamiclibrary.github.io/pages/anti_islam/immorality/killing.html' },
      { title: 'Offensive Jihad', url: 'https://islamiclibrary.github.io/pages/anti_islam/immorality/jihad.html' },
      { title: 'Expelling kuffar out of Arabia', url: 'https://islamiclibrary.github.io/pages/anti_islam/immorality/expelling.html' },
      { title: 'Spread by sword', url: 'https://islamiclibrary.github.io/pages/anti_islam/immorality/sword.html' },
      { title: 'Caravan raid', url: 'https://islamiclibrary.github.io/pages/anti_islam/immorality/caravan.html' },
      { title: 'Kinana umquirfa ummarawan swelam', url: 'https://islamiclibrary.github.io/pages/anti_islam/immorality/kinana.html' },
      { title: 'Building churches', url: 'https://islamiclibrary.github.io/pages/anti_islam/immorality/churches.html' },
      { title: 'Cutting thieves hands', url: 'https://islamiclibrary.github.io/pages/anti_islam/immorality/hands.html' },
      { title: 'Why was slavery allowed', url: 'https://islamiclibrary.github.io/pages/anti_islam/immorality/slavery.html' },
      { title: 'Treaties', url: 'https://islamiclibrary.github.io/pages/anti_islam/immorality/treaties.html' },
      { title: 'Dhul Khulasa Ghazwa', url: 'https://islamiclibrary.github.io/pages/anti_islam/immorality/Dhul.html' },
      { title: 'Temples of mushrikin destroyed under shariah', url: 'https://islamiclibrary.github.io/pages/anti_islam/immorality/temples.html' },
      { title: 'Prisoners of Badr', url: 'https://islamiclibrary.github.io/pages/anti_islam/immorality/prisoners.html' },
      { title: 'Drinking law', url: 'https://islamiclibrary.github.io/pages/anti_islam/immorality/drinking.html' },
      { title: 'Dealing kindly to non-muslims', url: 'https://islamiclibrary.github.io/pages/anti_islam/immorality/kindly.html' },
      { title: 'Olaysis nahr al dam ghazwa', url: 'https://islamiclibrary.github.io/pages/anti_islam/immorality/Olaysis.html' },
      { title: 'Muslim not killed for non-muslim', url: 'https://islamiclibrary.github.io/pages/anti_islam/immorality/killed.html' },
      { title: 'Hating disbelievers is wajib', url: 'https://islamiclibrary.github.io/pages/anti_islam/immorality/disbelievers.html' },
      { title: 'Treatment of the poor', url: 'https://islamiclibrary.github.io/pages/anti_islam/immorality/poor.html' },
      { title: 'Was al-khidr killing the child unfair', url: 'https://islamiclibrary.github.io/pages/anti_islam/immorality/al-khidr.html' },
      { title: 'Surah kahf 86 muddy spring', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_errors/surah_kahf_86.html' },
      { title: 'Surah muminun 14 embryology', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_errors/surah_muminun_14.html' },
      { title: 'Surah 86 6 sperm backbone', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_errors/surah_86_6.html' },
      { title: 'Surah mulk 5', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_errors/surah_mulk_5.html' },
      { title: 'Surah hijr 22', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_errors/surah_hijr_22.html' },
      { title: 'Surah al hajj 46', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_errors/surah_al_hajj_46.html' },
      { title: 'Surah yusuf 20 dirham', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_errors/surah_yusuf_20.html' },
      { title: 'Surah nahl 66 milk from cows stomach', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_errors/surah_nahl_66.html' },
      { title: 'Surah nisa 34 domestic abuse', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_explanation/Surah_nisa_34.html' },
      { title: 'Surah maryam 28 descendent', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_explanation/Surah_maryam_28.html' },
      { title: 'Surah imran 54 makr', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_explanation/Surah_imran_54.html' },
      { title: 'Contradictions', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_explanation/Contradictions.html' },
      { title: 'Surah Ahzab 50', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_explanation/Surah_Ahzab_50.html' },
      { title: 'Surah al tahrim 12', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_explanation/Surah_al_tahrim_12.html' },
      { title: 'Surah 78 33', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_explanation/Surah_78_33.html' },
      { title: 'Surah baqarah 282 women slow', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_explanation/Surah_baqarah_282.html' },
      { title: 'Surah maryam 83 sending demons', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_explanation/Surah_maryam_83.html' },
      { title: 'Surah rum false prophecy', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_explanation/Surah_rum_false_prophecy.html' },
      { title: 'Surah yassin 40 eclipse', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_explanation/Surah_yassin_40.html' },
      { title: 'Surah ahzab 53', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_explanation/Surah_ahzab_53.html' },
      { title: 'Surah ahqaf 46', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_explanation/Surah_ahqaf_46.html' },
      { title: 'Surah at tawbah 31 jesus god', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_explanation/Surah_at_tawbah_31.html' },
      { title: 'Surah 56 37', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_explanation/Surah_56_37.html' },
      { title: 'Surah talaq 4 child marriage', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_explanation/Surah_talaq_4.html' },
      { title: 'Surah tawbah 30 ezra god', url: 'https://islamiclibrary.github.io/pages/anti_islam/quran_explanation/Surah_tawbah_30.html' },
      { title: 'Isra Miraj', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/isra_miraj.html' },
      { title: 'Mans water', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/mans_water.html' },
      { title: '7 earths', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/7_earths.html' },
      { title: 'Bukhari 3199 top of creation', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/bukhari_3199.html' },
      { title: 'Sun orbits earth', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/sun_orbits.html' },
      { title: 'Camel pee', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/camel_pee.html' },
      { title: 'Fly hadith', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/fly_hadith.html' },
      { title: 'Mountains fixing up earth', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/mountains_fixing.html' },
      { title: 'Sky has pillars', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/sky_pillars.html' },
      { title: 'Surah 51:49', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/surah_51_49.html' },
      { title: 'Surah 41:11', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/surah_41_11.html' },
      { title: 'Surah 71:16 moon has its own light', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/surah_71_16.html' },
      { title: 'Moon split', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/moon_split.html' },
      { title: '7 Ajwa dates', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/7_dates.html' },
      { title: '360 joints', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/360_joints.html' },
      { title: 'Flat earth', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/flat_earth.html' },
      { title: 'Global flood', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/global_flood.html' },
      { title: 'Man from clay', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/man_from_clay.html' },
      { title: '60 cubits height of Adam pbuh', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/60_cubits.html' },
      { title: 'Earth lays on a whale', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/earth_whale.html' },
      { title: 'Fevers from hellfire', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/fevers_hellfire.html' },
      { title: 'Hellfire having two breaths', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/hellfire_two_breaths.html' },
      { title: '6 days of creation', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/6days.html' },
      { title: 'Meat spoil because of the children of Israel', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/meat.html' },
      { title: 'Barrier between two seas', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/barrier.html' },
      { title: 'Moon landing rejected 55:33', url: 'https://islamiclibrary.github.io/pages/anti_islam/science_errors/Moon_landing.html' },
      { title: 'The last prophet', url: 'https://islamiclibrary.github.io/pages/islamic_sects/ahmadiyya/last.html' },
      { title: 'Isa (AS) crucifixion', url: 'https://islamiclibrary.github.io/pages/islamic_sects/ahmadiyya/crucifixion.html' },
      { title: 'Who is Al Mahdi', url: 'https://islamiclibrary.github.io/pages/islamic_sects/ahmadiyya/mahdi.html' },
      { title: 'Blasphemy', url: 'https://islamiclibrary.github.io/pages/islamic_sects/ahmadiyya/blasphemy.html' },
      { title: 'Love for all hatred for none', url: 'https://islamiclibrary.github.io/pages/islamic_sects/ahmadiyya/love.html' },
      { title: 'False prophecies made by Mirza Ghulam Ahmed', url: 'https://islamiclibrary.github.io/pages/islamic_sects/ahmadiyya/false_prophecies.html' },
      { title: 'Hadith contradiction', url: 'https://islamiclibrary.github.io/pages/islamic_sects/quranists/contradiction.html' },
      { title: 'Code 19', url: 'https://islamiclibrary.github.io/pages/islamic_sects/quranists/code19.html' },
      { title: 'Follow Hadith', url: 'https://islamiclibrary.github.io/pages/islamic_sects/quranists/following_hadith.html' },
      { title: 'Sura Taubah is satanic', url: 'https://islamiclibrary.github.io/pages/islamic_sects/quranists/satanic.html' },
      { title: 'Dont write Hadiths', url: 'https://islamiclibrary.github.io/pages/islamic_sects/quranists/writing_hadith.html' },
      { title: 'Donkey meat', url: 'https://islamiclibrary.github.io/pages/islamic_sects/quranists/donkey_meat.html' },
      { title: 'Rashad messenger of god', url: 'https://islamiclibrary.github.io/pages/islamic_sects/quranists/rashad.html' },
      { title: 'Submitter definition god', url: 'https://islamiclibrary.github.io/pages/islamic_sects/quranists/submitter.html' },
      { title: 'Rashad contradicts Quran', url: 'https://islamiclibrary.github.io/pages/islamic_sects/quranists/rashad_contracition.html' },
      { title: "Questions quranists can't respond to", url: 'https://islamiclibrary.github.io/pages/islamic_sects/quranists/questions.html' },
      { title: 'How the Qiraat Refute Quranists', url: 'https://islamiclibrary.github.io/pages/islamic_sects/quranists/qiraat.html' },
      { title: 'How the Existence of Quranists Refutes Them', url: 'https://islamiclibrary.github.io/pages/islamic_sects/quranists/existence.html' },
      { title: 'Hadith Collections prior to Six Most Authentic Sunni Hadith Collections', url: 'https://islamiclibrary.github.io/pages/islamic_sects/quranists/collections.html' },
      { title: 'Hadith and politics', url: 'https://islamiclibrary.github.io/pages/islamic_sects/quranists/politics.html' },
      { title: 'Hadith reliability', url: 'https://islamiclibrary.github.io/pages/islamic_sects/quranists/reliability.html' },
      { title: 'Mutah', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/mutah.html' },
      { title: 'Creed', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/creed.html' },
      { title: 'Shias killed Hussain', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/shia_killed_hussain.html' },
      { title: 'Did Aisha (ra) kill Uthman (ra)?', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/aisha_kill_uthman.html' },
      { title: 'Umar (ra) ran from a battle?', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/umar_ran.html' },
      { title: 'Umar marriage', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/umar_marriage.html' },
      { title: 'The prophet (SAW) sucking Hassan', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/sucking_hassan.html' },
      { title: 'Wives are from Ahlulbayt', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/wives.html' },
      { title: 'Ali was not born in the Kaaba', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/ali_kaaba.html' },
      { title: 'Breaking Sawm', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/breaking_sawm.html' },
      { title: 'Camel urine in Shiism', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/camel_urine.html' },
      { title: 'Taraweeh is Sunnah', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/taraweeh.html' },
      { title: 'Ashura and Karbala', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/ashura_karbala.html' },
      { title: 'Najd', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/najd.html' },
      { title: 'Fatima angry at Abu Bakr (ra)?', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/fatima_angry_abubakr.html' },
      { title: 'Prophet (SAW) getting touched by naked women?', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/naked_women.html' },
      { title: 'Men breastfeeding men?', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/breastfeeding.html' },
      { title: 'Fatima angry at Ali (ra)?', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/fatima_angry_ali.html' },
      { title: 'Aisha (ra) breastfeeding', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/aisha_breastfeeding.html' },
      { title: 'Aisha (ra) and Hafsa', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/aisha_hafsa.html' },
      { title: 'Prophets vs Imams', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/prophets_imams.html' },
      { title: 'Pen and paper', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/pen_paper.html' },
      { title: 'Mu’āwiyah died with a cross on his neck?', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/muawiyah_cross.html' },
      { title: 'Lies shias claim about Imam Abu Hanifa', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/abu_hanifa.html' },
      { title: 'Umar (ra) was gay', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/umar_gay.html' },
      { title: 'Sifaat of Allah in shia narrations', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/sifaat.html' },
      { title: 'Khomeini insults Muhammad (SAW)', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/khomeini.html' },
      { title: 'Taqiyyah in Shiism', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/taqiyyah.html' },
      { title: 'Racism in Shiism', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/racism.html' },
      { title: 'Cannibalism in Shiism', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/cannibalism.html' },
      { title: 'Whale Hadith', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/whale_hadith.html' },
      { title: 'Pigeons', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/pigeons.html' },
      { title: 'Donkey-Isnaad', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/donkey-isnaad.html' },
      { title: 'A tranny will kill Imam Mahdi', url: 'https://islamiclibrary.github.io/pages/islamic_sects/shiism/tranny.html' },
      { title: 'Hanafi', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/four_madhabs/hanafi.html' },
      { title: 'Hanbali', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/four_madhabs/hanbali.html' },
      { title: 'Shafii', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/four_madhabs/shafii.html' },
      { title: 'Maliki', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/four_madhabs/maliki.html' },
      { title: 'Madhabs', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/four_madhabs/madhabs.html' },
      { title: 'Aisha is in Paradise', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/sahaba_merits/aisha_paradise.html' },
      { title: 'Aisha merits', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/sahaba_merits/aisha_merits.html' },
      { title: 'Umar merits', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/sahaba_merits/umar_merits.html' },
      { title: 'Abu Bakr merits', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/sahaba_merits/abubakr_merits.html' },
      { title: 'Muawiayah is in Paradise', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/sahaba_merits/muawiyah_paradise.html' },
      { title: 'Fatima merits', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/sahaba_merits/fatima_merits.html' },
      { title: 'Ali merits', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/sahaba_merits/ali_merits.html' },
      { title: 'Uthman merits', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/sahaba_merits/uthman_merits.html' },
      { title: 'Hasan merits', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/sahaba_merits/hasan_merits.html' },
      { title: 'Hasan, Hussein and Muawiyah', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/sahaba_merits/hasan_hussein_muawiyah.html' },
      { title: 'Muawiayah cursing Ali', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/sahaba_merits/muawiyah_cursing.html' },
      { title: 'Muawiyah merits', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/sahaba_merits/muawiyah_merits.html' },
      { title: 'The Sunnah of Muhammad (peace and blessings be upon him) and his Sahaba (may Allah be pleased with them)', url: 'https://islamiclibrary.github.io/pages/muslim_mustknow/sahaba_merits/sunnah.html' },
      { title: 'Proof for god', url: 'https://islamiclibrary.github.io/pages/other_beliefs/atheism/proof.html' },
      { title: 'Objective morality', url: 'https://islamiclibrary.github.io/pages/other_beliefs/atheism/morality.html' },
      { title: 'Is eternal hell unjust?', url: 'https://islamiclibrary.github.io/pages/other_beliefs/atheism/eternal_hell.html' },
      { title: '"We are just some cells"', url: 'https://islamiclibrary.github.io/pages/other_beliefs/atheism/cells.html' },
      { title: 'Scientific proof for god', url: 'https://islamiclibrary.github.io/pages/other_beliefs/atheism/scientific_god.html' },
      { title: 'Is god evil?', url: 'https://islamiclibrary.github.io/pages/other_beliefs/atheism/evil_god.html' },
      { title: 'Fitrah', url: 'https://islamiclibrary.github.io/pages/other_beliefs/atheism/Fitrah.html' },
      { title: 'Philosophical arguments for god\'s existence', url: 'https://islamiclibrary.github.io/pages/other_beliefs/atheism/philosophical_god.html' },
      { title: '"There are thousands of religions"', url: 'https://islamiclibrary.github.io/pages/other_beliefs/atheism/1000_religions.html' },
      { title: 'Refuting Deism', url: 'https://islamiclibrary.github.io/pages/other_beliefs/atheism/deism.html' },
      { title: 'Rational faculties', url: 'https://islamiclibrary.github.io/pages/other_beliefs/atheism/rationality.html' },
      { title: 'Philosophy of science', url: 'https://islamiclibrary.github.io/pages/other_beliefs/atheism/science.html' },
      { title: 'The problem of consciousness', url: 'https://islamiclibrary.github.io/pages/other_beliefs/atheism/consciousness.html' },
      { title: 'Dogmas in science', url: 'https://islamiclibrary.github.io/pages/other_beliefs/atheism/science_dogmas.html' },
      { title: 'Evolution human ancestral species', url: 'https://islamiclibrary.github.io/pages/other_beliefs/atheism/evolution_human.html' },
      { title: 'Genetic similarity', url: 'https://islamiclibrary.github.io/pages/other_beliefs/atheism/Genetic_similarity.html' },
      { title: 'Refuting the proofs for Darwinism', url: 'https://islamiclibrary.github.io/pages/other_beliefs/atheism/darwinism_proof.html' },
      { title: 'Evolution does not disprove Islam even if true', url: 'https://islamiclibrary.github.io/pages/other_beliefs/atheism/islamic_evolution.html' },
      { title: 'erv common ancestry', url: 'https://islamiclibrary.github.io/pages/other_beliefs/atheism/erv_common_ancestry.html' },
      { title: 'Evolution is a social paradigm', url: 'https://islamiclibrary.github.io/pages/other_beliefs/atheism/social_paradigm.html' },
      { title: 'Homophobia and Bigotry', url: 'https://islamiclibrary.github.io/pages/other_beliefs/atheism/Homophobia.html' },
      { title: 'Short rebuttals to common atheistic arguments', url: 'https://islamiclibrary.github.io/pages/other_beliefs/atheism/Short.html' },
      { title: 'Contradiction in core belief', url: 'https://islamiclibrary.github.io/pages/other_beliefs/buddhism/Contradiction.html' },
      { title: 'Morality in Buddhism', url: 'https://islamiclibrary.github.io/pages/other_beliefs/buddhism/Morality.html' },
      { title: 'Incoherence of Buddhism', url: 'https://islamiclibrary.github.io/pages/other_beliefs/buddhism/Incoherence.html' },
      { title: 'Meditation in Buddhism is not reliable', url: 'https://islamiclibrary.github.io/pages/other_beliefs/buddhism/Meditation.html' },
      { title: 'Women in Buddhism', url: 'https://islamiclibrary.github.io/pages/other_beliefs/buddhism/Women.html' },
      { title: 'Buddhism says Buddhism can be false', url: 'https://islamiclibrary.github.io/pages/other_beliefs/buddhism/false.html' },
      { title: 'Contradictions in Hindu scriptures', url: 'https://islamiclibrary.github.io/pages/other_beliefs/hinduism/contradictions.html' },
      { title: 'Scientific errors', url: 'https://islamiclibrary.github.io/pages/other_beliefs/hinduism/science.html' },
      { title: 'Refuting Hindu veganism', url: 'https://islamiclibrary.github.io/pages/other_beliefs/hinduism/veganism.html' },
      { title: 'Disgusting Hindu deities', url: 'https://islamiclibrary.github.io/pages/other_beliefs/hinduism/disguisting.html' },
      { title: 'Women in Hinduism', url: 'https://islamiclibrary.github.io/pages/other_beliefs/hinduism/women.html' },
      { title: 'Hindutva exposed', url: 'https://islamiclibrary.github.io/pages/other_beliefs/hinduism/hindutva.html' },
      { title: 'Repulsive things in Hinduism', url: 'https://islamiclibrary.github.io/pages/other_beliefs/hinduism/repulsive.html' },
      { title: 'Corruption in Hindu scriptures', url: 'https://islamiclibrary.github.io/pages/other_beliefs/hinduism/corruption.html' },
      { title: 'Slavery in Hinduism', url: 'https://islamiclibrary.github.io/pages/other_beliefs/hinduism/slavery.html' },
      { title: 'The caste system', url: 'https://islamiclibrary.github.io/pages/other_beliefs/hinduism/caste.html' },
      { title: 'Refuting reincarnation in Hinduism', url: 'https://islamiclibrary.github.io/pages/other_beliefs/hinduism/reincarnation.html' },
      { title: 'Refuting Hindu astrology', url: 'https://islamiclibrary.github.io/pages/other_beliefs/hinduism/astrology.html' },
      { title: 'Exclusivity of salvation in Hinduism + Blasphemy and apostasy laws', url: 'https://islamiclibrary.github.io/pages/other_beliefs/hinduism/law.html' },
      { title: 'Child marriage', url: 'https://islamiclibrary.github.io/pages/other_beliefs/hinduism/child.html' },
      { title: 'Introduction', url: 'https://islamiclibrary.github.io/pages/preservation/textual/intro.html' },
      { title: 'Abu Bakr Compilation', url: 'https://islamiclibrary.github.io/pages/preservation/textual/abubakr.html' },
      { title: 'Uthman Compilation', url: 'https://islamiclibrary.github.io/pages/preservation/textual/uthman.html' },
      { title: '7 Ahruf', url: 'https://islamiclibrary.github.io/pages/preservation/textual/ahruf.html' },
      { title: 'Addressing common arguments', url: 'https://islamiclibrary.github.io/pages/preservation/textual/arguments.html' },
      { title: 'Other important information', url: 'https://islamiclibrary.github.io/pages/preservation/textual/info.html' },
      { title: 'What academics say', url: 'https://islamiclibrary.github.io/pages/preservation/textual/academics.html' },
      { title: 'Books & Resources', url: 'https://islamiclibrary.github.io/pages/preservation/textual/books.html' },
      { title: 'Reliability of Imam Hafs', url: 'https://islamiclibrary.github.io/pages/preservation/textual/hafs.html' },
      { title: 'Muhammad ﷺ in the Bible', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/Muhammad_SAW_bible.html' },
      { title: 'Incoherent Incarnation', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/incarnation.html' },
      { title: 'Biblical corruption', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/corruption.html' },
      { title: 'Theological Inconsistencies', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/inconsistencies.html' },
      { title: 'Textual criticism', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/criticism.html' },
      { title: 'Origins of Christianity', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/origins.html' },
      { title: 'Polygamy', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/polygamy.html' },
      { title: 'Preservation claims', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/preservation_claims.html' },
      { title: 'Unity and diversity in the New Testament', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/unity_diversity.html' },
      { title: 'Crucifixion', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/crucifixion.html' },
      { title: 'Simon Peter in script and memory', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/simon_peter.html' },
      { title: 'Trinity not in scripture', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/trinity_missing.html' },
      { title: 'Pagan origins of the Trinity', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/pagan_trinity.html' },
      { title: 'Apostasy law', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/apostasy.html' },
      { title: 'Anonymous authors', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/anonymous.html' },
      { title: 'Hajj Makkah Mecca Mekka in the Bible', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/hajj.html' },
      { title: 'Is Jesus god according to the Quran?', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/jesus_god_quran.html' },
      { title: 'Refuting resurrection', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/resurrection.html' },
      { title: 'Pedophilia in the Bible', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/pedophilia.html' },
      { title: 'Sacrifice is not always needed', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/sacrifice.html' },
      { title: 'Tawheed in Quran and Hadith', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/tawheed.html' },
      { title: 'False prophecies in the Bible', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/false_prophecies.html' },
      { title: 'Women in Christianity', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/women.html' },
      { title: 'Jehovas witnesses', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/jehovas_witnesses.html' },
      { title: 'Was Jesus AS divine?', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/jesus_divinity.html' },
      { title: 'Bible contradictions and errors', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/contradictions_errors.html' },
      { title: 'Refuting crucifixion prophecies in the OT', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/crucifixion_prophecies.html' },
      { title: 'Lies of Matthew', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/matthews_lies.html' },
      { title: 'Fake prophecy of Luke 24:46', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/luke_24_46.html' },
      { title: 'Gospel authors manipulation of verses', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/verse_manipulation.html' },
      { title: 'Alleged trinitarian verses in the OT', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/trinitarian_verses.html' },
      { title: 'Falsehood enhances god', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/gods_falsehood.html' },
      { title: 'Assurance of salvation', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/salvation_assurance.html' },
      { title: 'Importance of monotheism', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/monotheisms_importance.html' },
      { title: 'The father and I are one', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/father_one.html' },
      { title: 'Did the Quran copy the infancy gospels?', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/quran_infancy_gospels.html' },
      { title: 'Logical problem of the trinity', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/trinity_problem.html' },
      { title: 'The contingency argument refutes Christianity', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/contingency_problem.html' },
      { title: 'Is the trinity necessary because of love?', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/trinity_love.html' },
      { title: 'Biblical Jesus AS is a warlord', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/jesus_warlord.html' },
      { title: 'Biblical Hudood', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/hudood.html' },
      { title: 'Can Christians be friends with non-Christians', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/friends.html' },
      { title: 'God defeating death', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/god_death.html' },
      { title: 'The sacrifice dilemma', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/sacrifice_dilemma.html' },
      { title: 'The Trinity can not exist', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/trinity_impossibility.html' },
      { title: 'Contradictions of the Trinity', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/trinity_contradictions.html' },
      { title: 'The dream argument', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/dream.html' },
      { title: 'Refuting Mormonism', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/mormonism.html' },
      { title: 'Biblical god doesn\'t love everyone', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/no_love.html' },
      { title: 'Surah 4 Verse 157', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/surah4.html' },
      { title: '"600 years later"', url: 'https://islamiclibrary.github.io/pages/religion_debunking/christianity/600.html' },
      { title: 'Deuteronomy 18 prophecy', url: 'https://islamiclibrary.github.io/pages/religion_debunking/judaism/Deuteronomy.html' },
      { title: 'Genesis 17:20', url: 'https://islamiclibrary.github.io/pages/religion_debunking/judaism/Genesis.html' },
      { title: 'Blasphemies in Judaism', url: 'https://islamiclibrary.github.io/pages/religion_debunking/judaism/Blasphemies.html' },
      { title: 'Injustice towards prophets in Judaism', url: 'https://islamiclibrary.github.io/pages/religion_debunking/judaism/Injustice.html' },
      { title: 'Black magic in Judaism', url: 'https://islamiclibrary.github.io/pages/religion_debunking/judaism/magic.html' },
      { title: 'Abrogation in Jewish theology', url: 'https://islamiclibrary.github.io/pages/religion_debunking/judaism/Abrogation.html' },
      { title: 'Anti-zionist Rabbis', url: 'https://islamiclibrary.github.io/pages/religion_debunking/judaism/anti-zionist.html' },
      { title: 'Talmud condemns Zionism', url: 'https://islamiclibrary.github.io/pages/religion_debunking/judaism/talmud.html' },
      { title: 'Truth about Zionism', url: 'https://islamiclibrary.github.io/pages/religion_debunking/judaism/truth.html' },
      { title: 'Errors in Tanakh and Talmud', url: 'https://islamiclibrary.github.io/pages/religion_debunking/judaism/errors.html' },
      { title: 'Proof Isa ibn Maryam peace be upon him is the Messiah', url: 'https://islamiclibrary.github.io/pages/religion_debunking/judaism/messiah.html' },
      { title: 'Transmission of the Torah', url: 'https://islamiclibrary.github.io/pages/religion_debunking/judaism/Transmission.html' },
      { title: 'Rabbi worship in Judaism', url: 'https://islamiclibrary.github.io/pages/religion_debunking/judaism/rabbi.html' },
      { title: 'Daniel 7:13 Islam prophecy', url: 'https://islamiclibrary.github.io/pages/religion_debunking/judaism/daniel.html' },
      { title: 'Contradiction of the Sikh god', url: 'https://islamiclibrary.github.io/pages/religion_debunking/sikhism/contradiction.html' },
      { title: 'Guru Nanak exposed', url: 'https://islamiclibrary.github.io/pages/religion_debunking/sikhism/guru.html' },
      { title: 'Polygamy in Sikhism', url: 'https://islamiclibrary.github.io/pages/religion_debunking/sikhism/polygamy.html' },
      { title: 'Equality in Sikhism debunked', url: 'https://islamiclibrary.github.io/pages/religion_debunking/sikhism/equality.html' },
      { title: 'Refuting Veganism in Sikhism', url: 'https://islamiclibrary.github.io/pages/religion_debunking/sikhism/veganism.html' },
      { title: 'Shirk in Sikhism', url: 'https://islamiclibrary.github.io/pages/religion_debunking/sikhism/shirk.html' },
      { title: 'Refuting karma and reincarnation in Sikhism', url: 'https://islamiclibrary.github.io/pages/religion_debunking/sikhism/karma.html' },
      { title: 'Sikh militancy', url: 'https://islamiclibrary.github.io/pages/religion_debunking/sikhism/militancy.html' },
      { title: 'Child marriage in Sikhism', url: 'https://islamiclibrary.github.io/pages/religion_debunking/sikhism/child.html' },
      { title: 'Exclusivism in Sikhism', url: 'https://islamiclibrary.github.io/pages/religion_debunking/sikhism/exclusivism.html' },
      { title: 'Sexual metaphors of the Sikh god', url: 'https://islamiclibrary.github.io/pages/religion_debunking/sikhism/sexual.html' },
      { title: 'Inauthenticity of Sikh texts', url: 'https://islamiclibrary.github.io/pages/religion_debunking/sikhism/inauthenticity.html' }
    ]; // Replace with your actual search data or logic

    const filteredResults = mockData.filter(result =>
        result.title.toLowerCase().includes(searchTerm)
    );

    displayResults(filteredResults);
});

function displayResults(results) {
    if (results.length === 0) {
        searchResults.innerHTML = 'No results found.';
    } else {
        const resultList = document.createElement('ul');
        results.forEach(result => {
            const listItem = document.createElement('li');
            listItem.textContent = result.title;

            // Add a click event listener to each result item
            listItem.addEventListener('click', function() {
                window.location.href = result.url;
            });

            resultList.appendChild(listItem);
        });
        searchResults.innerHTML = ''; // Clear previous results
        searchResults.appendChild(resultList);
        searchResults.style.backgroundColor = '#fff';
        searchResults.style.border = '2px solid #ccc';
    }
}
console.log("Mein JavaScript-Skript wurde geladen.");
